### ISSUE TITLE
Contact Data are missing

### ISSUE THREAD

**Issue by DigniticeRoland** [joshuatz/linkedin-to-jsonresume#10]
Thank you very much for the great project and what an honor to open the #10 issue. I think you missed the contact data. In case you have a direct connection to the profile, in most cases, you are allowed to see the email address and other connected profiles e.g. Twitter. Unfortunately, I can't find this information in the JSON file. Is that a bug or a feature? Thank you

**Comment by joshuatz** [comment]
@DigniticeRoland Thanks for bringing this to my attention.

I've improved the contact information scraping; it should now pull in Twitter accounts, email address (it was already, but some of the code was faulty), and phone number, when applicable. Change was implemented in v0.0.7, but I'm pushing v0.0.8 now to the chrome webstore for distribution.

I've tested it myself, and it seems to be working on a few profiles I've found that have those pieces of their profile filled in. Feel free to test yourself once your browser receives the update push from Google, or, since that could take up to a week or so (it has to be reviewed), you can "sideload" the new version.

Side-loading instructions:
1. Downloading [this zip from the release](https://github.com/joshuatz/linkedin-to-jsonresume/releases/download/v0.0.8/build_0.0.8.zip)
2. Go to Chrome's extension setting page (`chrome://extensions`)
3. Turn on developer mode (upper right toggle switch)
4. Drag the downloaded zip to the browser to let it install
5. Test it out, then uninstall

I'll leave this issue open until I see that the update has propagated and I confirm it works, or if you can confirm yourself.

**Comment by joshuatz** [comment]
Closing - looks like Chrome webstore accepted new release, and is working on my end.
