### ISSUE TITLE
Certificates are missing

### ISSUE THREAD

**Issue by DigniticeRoland** [joshuatz/linkedin-to-jsonresume#14]
The block of certificates is missing. I mean some people have a list of certificates like coursera.

![image](https://user-images.githubusercontent.com/62964017/79140980-30d66480-7db9-11ea-9b85-8a5bdbbd5dd6.png)

**Comment by joshuatz** [comment]
This was originally by design, and not a bug. The official JSON Resume specification currently does not actually have any relevant section where certificates could placed. As such, I opted to omit it from both scraping and output.

I'm updating the code to include certificates, as you are requesting, but only if the `exportBeyondSpec` flag is set to true, since I don't want to violate the codified schema of JSON Resume.

The good news is that JSON Resume will likely be adding an official section for certificates soon (see [PR #340](https://github.com/jsonresume/resume-schema/pull/340) in the schema repo) - once that change is live, I can update the extension to automatically always include certificates in the output.
