### ISSUE TITLE
Non-primary languages

### ISSUE THREAD

**Issue by dev-plvlml** [joshuatz/linkedin-to-jsonresume#18]
Hi,
It would be really nice to add support for non-primary language profiles.
E.g., my primary language of a LinkedIn profile is Russian, but it has an English version too (obtained with a cgi `?locale=en_US`).
BTW, the official PDF exporting fails here too and always exports a (primary) Russian version, even I switch to an English page.

**Comment by joshuatz** [comment]
To clarify, did you use the ["add profile in another language" feature](https://www.linkedin.com/help/linkedin/answer/1717/create-or-delete-a-profile-in-another-language) to build a separate English version of your profile, and that is what you want an export of, instead of Russian?

Also, do you mind adding [my profile](https://www.linkedin.com/in/joshuatzucker/) on LinkedIn, or just sharing your profile URL if it is public? Or, just posting the URL of another public profile you have found with this issue? I'm having some trouble finding a profile to test with that would have this issue.

**Comment by dev-plvlml** [comment]
> To clarify, did you use the "add profile in another language" feature to build a separate English version of your profile, and that is what you want an export of, instead of Russian?

Yes, that is exactly  the case.

> Also, do you mind adding my profile on LinkedIn, or just sharing your profile URL if it is public?

Surely, it's [plvlml](https://www.linkedin.com/in/plvlml/).

**Comment by joshuatz** [comment]
@dev-plvlml Thanks for the details (and for the LI add 😃)!

I'm looking into this; an interesting thing is that LinkedIn is clearly choosing to go with the language of the person looking at the profile, not the profile itself. When I pull up your profile, I have the opposite problem that you do - it will only let me get an English export, and I can't get it to export Russian.

That being said, I think I might already see a solution I can use. I'll keep you posted.

**Comment by joshuatz** [comment]
@dev-plvlml Thanks again for bringing this to my attention, and sharing your profile with me.

This has now been implemented, and is in the newest `v1.0.0` release. I've uploaded it to the Chrome webstore for distribution, but it can take weeks to get processed, so if you want to use it ASAP, you can follow [my side-loading instructions](https://github.com/joshuatz/linkedin-to-jsonresume#chrome-side-loading-instructions).
