### ISSUE TITLE
Projects fail to export

### ISSUE THREAD

**Issue by SKalt** [joshuatz/linkedin-to-jsonresume#33]
I'd leave steps to reproduce, but I'm trying to keep my profile private for the time being.  While I figure that out: I had several projects listed, and I got an empty list.

**Comment by joshuatz** [comment]
This is actually by design; there are multiple things (projects and certificates) that I coded into this tool to collect, but opted not to include in the output because (at the time) they were not part of the "official" JSON Resume specification, and my goal was to stay as true to that as possible.

I'm trying to look to see if that has changed and projects is now "official", but tracking the state of the schema is a little... uh... confusing. Looking at my code, I believe at that time I was coding this I was going off [this comment](https://github.com/jsonresume/resume-schema/issues/296#issuecomment-349074937), which made it clear `v1` was not ready, and `v0` was the only official release so far. I believe I split the difference and coded the tool to export `v0`, but at the same time, included some of the latest schema in my definition files and internals, which at the time was [`v0.1.3`](https://github.com/jsonresume/resume-schema/blob/v0.1.3/schema.json). All this is in my comment block [at the top of my TS definition file](https://github.com/joshuatz/linkedin-to-jsonresume/blob/e557cb15bc442ce7700cd5d4c45b3024106a0524/jsonresume.schema.ts#L1-L6).

Unfortunately, things are **still** a bit unclear to me. The [schema repo](https://github.com/jsonresume/resume-schema) makes it look like `v1.0.0` is still under active development, and not stable. The most recent clarifying comment I could find is [this one](https://github.com/jsonresume/resume-schema/issues/386#issuecomment-658829786) (July 15th), which makes it sound like `v0.0.16` ([permalink](https://github.com/jsonresume/resume-schema/blob/a6d1ae5c990e3370de6ca305ef32477b9516391b/schema.json), [tag link](https://github.com/jsonresume/resume-schema/blob/v0.0.16/schema.json)) is the *"official"* version. And, getting back to your issue, that version *also* does not have projects implemented yet. As an added wrinkle, the version hosted at [json.schemastore.org/resume](https://json.schemastore.org/resume) is definitely ***not*** `v0.0.16`.

---

Sorry for the wall of text; a lot of this is just me leaving notes for myself as I work through why I made the decision I did.

I suppose, what I could do (if I have the time at some point to implement it) is give an option to users of my extension when generating an export that lets them pick between the older "stable" version of the schema (this would be the default option), or the newest version (that I have coded support for). Currently, I actually kind of do this, although [it is hidden behind a flag](https://github.com/joshuatz/linkedin-to-jsonresume/blob/e557cb15bc442ce7700cd5d4c45b3024106a0524/src/main.js#L778) you would have to set by opening your browser console and setting it via JS. The ideal version would just be a dropdown in the popup or something like that.

**Comment by SKalt** [comment]
> Unfortunately, things are still a bit unclear to me.
Your research has certainly made things clearer to me! I'd be down to help support multiple schema versions.

**Comment by joshuatz** [comment]
Had some time to work on this and actually got a lot done this morning - tracked on PR #34.

The remaining work is to integrate the picker into the UI and pass the option as part of the extension message to the script context; shouldn't take long to do, and I should probably have time in the next day or two to finish it up.

**Comment by joshuatz** [comment]
Multiple schema support has been shipped 🚀 --> [Release v2.0.0](https://github.com/joshuatz/linkedin-to-jsonresume/releases/tag/v2.0.0)
