### ISSUE TITLE
Collects wrong Job Title and company

### ISSUE THREAD

**Issue by jacobamiller** [joshuatz/linkedin-to-jsonresume#38]
When a person has more than one current job, the system scrapes the last job, however, the profile "Professional Headline"  Company & location are from the 1st job normally their main job 

Picked Job
< h3 class="t-16 t-black t-bold">Founder - 3D Film Director</h3>

Actualy main job
< h2 class="mt1 t-18 t-black t-normal break-words">
            Supply Chain &amp; Business Development Consultant at Island Rush - Singapore
          </h2>
or 
< h3 class="t-16 t-black t-bold">Supply Chain &amp; Business Development Consultant</h3>

**Comment by joshuatz** [comment]
@jacobamiller Thanks for reporting; should be fixed now, [released as v2.1.1](https://github.com/joshuatz/linkedin-to-jsonresume/releases/tag/v2.1.1) - update pushed to Chrome Web Store for distribution.

Notes: This was a regression because of the use of the newer Dash endpoints; they don't seem to preserve order in nested results (and, in fact, might invert them), and the only way to guarantee correct order is to use the provided intermediate table of contents elements (which was the fix implemented to close this issue).
