### ISSUE TITLE
Something Broke - Chrome Extension no longer working 

### ISSUE THREAD

**Issue by jacobamiller** [joshuatz/linkedin-to-jsonresume#39]
![Linkedin JSON](https://user-images.githubusercontent.com/24448077/105335430-9d18ab00-5c0a-11eb-8e6a-566ce3ff401e.jpg)

**Comment by joshuatz** [comment]
@jacobamiller I started looking into this, but I cannot (despite multiple attempts) replicate this on my end. It could be that I'm missing something that is unique to your usage that is breaking it for you, but not for me. So, a few questions / things to verify:

1. Does the URL of the profile you are on start with `https://www.linkedin.com/in/`?
2. Have you recently installed any new extensions in Chrome? If so, does disabling them fix the issue with mine?
3. Is there anything "*special*" about the profile you are on? Is it someone that has a mostly *private* profile and you are not connected with them?

**Comment by jacobamiller** [comment]
1. Does the URL of the profile you are on start with https://www.linkedin.com/in/?
--- Yes, standard profile 
2. Have you recently installed any new extensions in Chrome? If so, does disabling them fix the issue with mine?
----No, not that I'm aware of maybe in the background
3. Is there anything "special" about the profile you are on? Is it someone that has a mostly private profile and you are not connected with them?
--- No nothing special and tried on 10 others

I just uninstalled, rebooted, and re-installed now it is working back as normal, not clear what happened

**Comment by joshuatz** [comment]
Huh, interesting. Off the top of my head, there are a number of things that could have caused a *temporary* glitch like that, and some of them could be hyper-isolated to your account (for example, if LinkedIn rate-limited your account for certain API endpoints that I use).

I'm going to close this issue, since it is back to working for you, but of course feel free to re-open this (or create a new issue) if you encounter difficulties again. I'll also work on some standard troubleshooting steps I can provide you (or other users) if this happens again.
