### ISSUE TITLE
Candidate in lot

### ISSUE THREAD

**Issue by financeirotalenses** [joshuatz/linkedin-to-jsonresume#48]
o How difficult would it be to parse linketin to json in candidate groups, for example, search for a term and on the linkedin search page to be able to parse all candidates

would you have any tips on how i could implement it?

**Comment by joshuatz** [comment]
Not necessarily that difficult; you could modify some of the functions, such as `parseViaInternalApi`, to take a profile ID or URL, instead of assuming that the desired profile is the current page.

However, that is outside the scope of this extension and not something I am interested in pursuing or advising on, as it violates LinkedIn's TOS and something I'm not personally a fan of either. If you really want this kind of functionality, there are multiple commercial (paid) tools out there that already offer this kind of functionality.
