### ISSUE TITLE
Issue in export to Json

### ISSUE THREAD

**Issue by ayazali23** [joshuatz/linkedin-to-jsonresume#63]
https://www.linkedin.com/in/noamgraetz/
please check I Cannot export to Json like these types of profiles?

**Comment by joshuatz** [comment]
Hmm. I think there is actually a site-wide issue with the tool at the moment; not just that profile, but every profile (or at least ones that require an API endpoint). At a quick glance, this looks to be an issue with the LinkedIn Voyager APIs changing.

I'll try to make time this week to tackle this. Hopefully this will be a quick fix, like just updating an endpoint URL, but I can't tell for sure right now.

**Comment by ayazali23** [comment]
Thank you so much for your help

**Comment by joshuatz** [comment]
@ayazali23 I finally had some time to work on this - should now be fixed in [the new `v3.2.2` release](https://github.com/joshuatz/linkedin-to-jsonresume/releases/tag/v3.2.2).

(For anyone wondering - yes, the endpoints did change. I also added some code to try and make it easier to "discover" them in the future, as well some documentation notes around some interesting new GraphQL flavored endpoints).
