### ISSUE TITLE
Can I use on my own app?

### ISSUE THREAD

**Issue by ralyodio** [joshuatz/linkedin-to-jsonresume#71]
I’m looking to use this in my svelte app to export LinkedIn profile as json resume. 

Do you have an example?

I’m not interested in browser extension.

**Comment by joshuatz** [comment]
I mean, technically there is nothing stopping anyone from using this outside of a browser extension - I've kept the extension part of it pretty isolated, and the `main.js` entry-point does not import any extension specific code. [The README mentions this](https://github.com/joshuatz/linkedin-to-jsonresume/blob/489f1c6122ff3737cb2e65719b650db527fbad3f/README.md#debugging) - you can actually copy the output of `/build/main.js` and paste it into the browser console, without the extension installed, and it should work.

That being said, due to many reasons (this was one of my earlier programming projects, I did not foresee the interest in it, etc.), I did a bad job of making this modular, so you would probably need to do some refactoring to get it to fit your needs.

**Comment by ralyodio** [comment]
That’s fine.  Does it still work?

**Comment by joshuatz** [comment]
@ralyodio Yes, it still works via `main.js` if that is what you mean. Otherwise I'm not sure exactly what the question is...
