### ISSUE TITLE
[URGENT] Extension not working anymore.

### ISSUE THREAD

**Issue by RonanCamus** [joshuatz/linkedin-to-jsonresume#72]
**Troubleshooting**
Before creating your issue, please run through the following troubleshooting steps to make sure this is not a temporary glitch or caused by a factor outside the control of this tool:

- [✅] If you have recently installed any new browser extensions, try temporarily disabling them to see if that fixes mine (sometimes extensions interfere with each other)
- [✅] Verify that LinkedIn has not rate-limited or banned your account. If you cannot load profiles, or get random error messages and blank pages, that is outside my control

**Describe the issue**
The tool isn't exporting the whole resume anymore. LinkedIn might have change something in their code.

**Help me reproduce your issue**
In order to expedite a bug fix, please help me narrow down what could be causing your issue by providing details that will let me replicate the same issue you saw:

- Where did this happen?
	- Standard, as usual. It started to fail since last night. Yesterday morning it was working fine.
- Is there anything special about the profile you were trying to extract?
	- No.
- How consistent is this issue?
	- It happens for me and every other tests I did (4 different profiles)

**Screenshots**
  
<img width="455" alt="image" src="https://user-images.githubusercontent.com/10685957/172585319-3bcdaf34-f1ce-4827-ac98-baf982136c9b.png">

**Comment by stevenz4** [comment]
Yes, same here, i cannot export my jsonResume from LinkedIn

**Comment by Pierre570** [comment]
it doesnt work on https://www.linkedin.com/feed/ but still work on https://www.linkedin.com/in/

**Comment by joshuatz** [comment]
@RonanCamus Thanks for filling out the issue template. I saw that you liked [Pierre570's comment above](https://github.com/joshuatz/linkedin-to-jsonresume/issues/72#issuecomment-1149841750) - does that mean that using the correct URL fixed this issue for you? I'm having trouble replicating this otherwise.

@stevenz4 I guess the same goes for you.

I'll work on adding instructions to the README and URL check in the extension to remind users that this only works on profile pages.

**Comment by RonanCamus** [comment]
Thanks @joshuatz, keep going your work is great.
Btw, it's working again now... Don't know how/why.

Cheers !
